- hosts: localhost
  become: true
  pre_tasks:
    - name: Update apt cache
      tags:
        - zsh
        - node
      apt:
        update_cache: true

  tasks:
    - include_tasks: tasks/zsh.yml
      tags: zsh
    - include_tasks: tasks/node.yml
      tags: node
